### ISSUE TITLE
BuggleWorld editor raises OutOfBound exceptions on invalid worlds

### ISSUE THREAD

**Issue by mquinson** [BuggleInc/PLM#308]
I was trying to resize my world, and that must be done by editing the text file. Then, I did it wrong, and there were some cells of the content that were out of the declared word. This resulted in the file not being loaded in the editor, no error message displayed, beside of that exception on the console:

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 9
	at plm.universe.GridWorld.setCell(GridWorld.java:77)
	at plm.universe.bugglequest.BuggleWorld.readFromFile(BuggleWorld.java:263)
	at plm.universe.bugglequest.BuggleWorld.readFromFile(BuggleWorld.java:116)
	at plm.universe.bugglequest.BuggleWorld.newFromFile(BuggleWorld.java:110)
	at plm.core.ui.editor.buggleeditor.Editor.loadMap(Editor.java:53)

We make world resizing more user-friendly.

**Comment by mquinson** [comment]
We now serialize the worlds in json directly, so this bug is gone
