### ISSUE TITLE
[BUG] missing some thread locking around the run button

### ISSUE THREAD

**Issue by mquinson** [BuggleInc/PLM#40]
If you click really quickly on the run button while visiting an exercise that is a bit long to load (lot of entities or need to load a scripting engine such as python while it was not loaded previously), you can easily manage to get an exception such as the following. For exemple, double-clicking on the run button of the Conditions exercise.

java.util.ConcurrentModificationException
	at java.util.AbstractList$Itr.checkForComodification(AbstractList.java:372)
	at java.util.AbstractList$Itr.remove(AbstractList.java:357)
	at jlm.core.model.LessonRunner.run(LessonRunner.java:58)

I think that it comes from the fact that the Game locking (disabling the buttons) is done in the runner thread, allowing the AWT thread to issue a second command before the first one locks the door. This should be done in the action handler, which should itself be synchronized, and double check that the door is not locked before proceeding.

**Comment by mquinson** [comment]
The swing client is gone, thus closing.
