### ISSUE TITLE
Existing lessons are not runnable after trying to add one (button in the right down corner)

### ISSUE THREAD

**Issue by Steamplume** [BuggleInc/PLM#439]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at plm.core.ui.ExerciseView.selectedWorldHasChanged(ExerciseView.java:174)
	at plm.core.model.Game.fireSelectedWorldHasChanged(Game.java:836)
	at plm.core.model.Game.setSelectedWorld(Game.java:560)
	at plm.core.model.Game.getSelectedWorld(Game.java:530)
	at plm.core.ui.WorldComboListAdapter.currentExerciseHasChanged(WorldComboListAdapter.java:60)
	at plm.core.model.Game.fireCurrentExerciseChanged(Game.java:824)
	at plm.core.model.Game.setCurrentExercise(Game.java:496)
	at plm.core.model.Game.setCurrentLesson(Game.java:468)
	at plm.core.model.Game.switchLesson(Game.java:384)
	at plm.core.ui.LessonOverview$1.actionPerformed(ChooseLessonDialog.java:196)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by mquinson** [comment]
This issue is gone with the java swing client.
